[ci] move html export to CircleCI

diff --git a/.circleci/web/htmlize b/.circleci/web/htmlize
--- a/.circleci/web/htmlize
+++ b/.circleci/web/htmlize
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-## Export script for documentation files.
+## htmlize HTML export script for documentation files.
 ##
 ## Copyright (c) 2012-2014 Sylvain Benner
 ## Copyright (c) 2014-2022 Sylvain Benner & Contributors
@@ -11,11 +11,19 @@
 ##
 ## License: GPLv3
 
-mkdir -p "/tmp/sdn/"
-echo_headline "Extract data out of documentation files into .sdn"
 emacs -batch \
-      -l /opt/spacetools/spacedoc/sdnize/sdnize \
-      -no-site-file \
-      -q \
-      ~/.emacs.d/ \
-      /tmp/sdn/
+      -l ~/.emacs.d/init.el \
+      -l ~/.emacs.d/core/core-documentation.el \
+      -f spacemacs/publish-doc
+if [ $? -ne 0 ]; then
+    echo "spacemacs/publish-doc failed"
+    exit 2
+fi
+
+if [ -d ~/.emacs.d/export/ ]
+then
+    echo "Export succeeded"
+else
+    echo "~/.emacs.d/export/ doesn't exist"
+    exit 2
+fi
